BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS aq_grid_points (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code varchar(64) NOT NULL,
  name varchar(255) NOT NULL,
  latitude double precision NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  longitude double precision NOT NULL CHECK (longitude BETWEEN -180 AND 180),
  source varchar(64) NOT NULL,
  grid_version varchar(64) NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_aq_grid_points_code UNIQUE (code)
);

CREATE INDEX IF NOT EXISTS idx_aq_grid_points_active_version
  ON aq_grid_points (active, grid_version);

CREATE TABLE IF NOT EXISTS air_quality_observations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grid_point_id uuid NOT NULL REFERENCES aq_grid_points(id) ON DELETE RESTRICT,
  source varchar(64) NOT NULL,
  source_observed_at timestamptz NOT NULL,
  ingested_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  aqi smallint,
  pm2_5 double precision,
  pm10 double precision,
  co double precision,
  no double precision,
  no2 double precision,
  o3 double precision,
  so2 double precision,
  nh3 double precision,
  raw_payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_air_quality_source_grid_observed
    UNIQUE (source, grid_point_id, source_observed_at)
);

CREATE INDEX IF NOT EXISTS idx_air_quality_grid_observed
  ON air_quality_observations (grid_point_id, source_observed_at);
CREATE INDEX IF NOT EXISTS idx_air_quality_ingested_at
  ON air_quality_observations (ingested_at);

CREATE TABLE IF NOT EXISTS weather_observations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grid_point_id uuid NOT NULL REFERENCES aq_grid_points(id) ON DELETE RESTRICT,
  source varchar(64) NOT NULL,
  source_observed_at timestamptz NOT NULL,
  ingested_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  temperature double precision,
  humidity double precision,
  pressure double precision,
  wind_speed double precision,
  wind_direction double precision,
  clouds double precision,
  rain double precision,
  raw_payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_weather_source_grid_observed
    UNIQUE (source, grid_point_id, source_observed_at)
);

CREATE INDEX IF NOT EXISTS idx_weather_grid_observed
  ON weather_observations (grid_point_id, source_observed_at);
CREATE INDEX IF NOT EXISTS idx_weather_ingested_at
  ON weather_observations (ingested_at);

COMMIT;
